function covidallcasesnhcc20220213 = importCasesData(filename, dataLines)
%IMPORTFILE Import data from a text file
%  COVIDALLCASESNHCC20220213 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  COVIDALLCASESNHCC20220213 = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  covidallcasesnhcc20220213 = importfile("\\file\Usersg$\gva31\Home\My Documents\GiorgiasSandpit\GiorgiasSimLeaky_Omicron\waning\covid_allcases_nhcc_2022-02-13.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Feb-2022 22:32:48

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 70);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["EPISURVNUMBER", "STATUS", "REPORTDATE", "SEX", "AGEINYEARS", "AGEGRP1", "ETHNICITYPRIORITISEDMPAMEU", "DHB", "PHS", "DIED", "DIEDDT", "EARLIESTDATE", "HOSP", "HOSPITALNAME", "HOSPDT", "ONSETDT", "OUTBREAKSETTING", "OUTBRKNO", "MODIFIEDDATETIME", "FITCLINDESC", "EPICONT", "EPICONTID", "HLTHSTAT", "ICU", "CONTID1", "CONTID2", "CONTID3", "CONTLOCATION", "CONTPROBCONF", "HEALTHWORKER", "DTARRIVED", "LASTCOUNTRY", "LASTDTDEPARTED", "LASTDTENTERED", "OVERSEAS", "SECCOUNTRY", "SECDTDEPARTED", "SECDTENTERED", "THIRDCOUNTRY", "THIRDDTDEPARTED", "THIRDDTENTERED", "SOURCE", "AGEGRP3", "LABCONF", "LABCONFDATE", "CONFPROBCASETYPE", "FLAGDIEDFROMDISEASE", "STATUSCHANGE", "STATUSCHANGESUMM", "ISOLATIONTYPE", "ISOLATIONFROMDATE", "ISOLATIONTODATE", "HOWDISCOV", "HOWDISCSPEC", "SUBCLUSTER", "ISOLATIONFACILITY", "LASTTESTDT", "LASTTESTRESULT", "PREGNANCY", "QUARSAMPLE", "QUARANTDT", "QUARANTSPEC", "QUARANTFACILITY", "CTVALUE", "HISTORICAL", "VENTREQD", "DISCHDT", "NHI_ETHNIC1", "NHI_ETHNIC2", "NHI_ETHNIC3"];
opts.VariableTypes = ["string", "categorical", "datetime", "categorical", "double", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "datetime", "categorical", "categorical", "categorical", "datetime", "double", "categorical", "datetime", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "string", "categorical", "string", "string", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "datetime", "categorical", "categorical", "categorical", "categorical", "categorical", "datetime", "string", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["EPISURVNUMBER", "DTARRIVED", "LASTDTDEPARTED", "LASTDTENTERED", "ISOLATIONTODATE"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["EPISURVNUMBER", "STATUS", "SEX", "AGEGRP1", "ETHNICITYPRIORITISEDMPAMEU", "DHB", "PHS", "DIED", "DIEDDT", "HOSP", "HOSPITALNAME", "HOSPDT", "OUTBRKNO", "FITCLINDESC", "EPICONT", "EPICONTID", "HLTHSTAT", "ICU", "CONTID1", "CONTID2", "CONTID3", "CONTLOCATION", "CONTPROBCONF", "HEALTHWORKER", "DTARRIVED", "LASTCOUNTRY", "LASTDTDEPARTED", "LASTDTENTERED", "OVERSEAS", "SECCOUNTRY", "SECDTDEPARTED", "SECDTENTERED", "THIRDCOUNTRY", "THIRDDTDEPARTED", "THIRDDTENTERED", "SOURCE", "AGEGRP3", "LABCONF", "CONFPROBCASETYPE", "FLAGDIEDFROMDISEASE", "STATUSCHANGE", "STATUSCHANGESUMM", "ISOLATIONTYPE", "ISOLATIONTODATE", "HOWDISCOV", "HOWDISCSPEC", "SUBCLUSTER", "ISOLATIONFACILITY", "LASTTESTDT", "LASTTESTRESULT", "PREGNANCY", "QUARSAMPLE", "QUARANTDT", "QUARANTSPEC", "QUARANTFACILITY", "CTVALUE", "HISTORICAL", "VENTREQD", "DISCHDT", "NHI_ETHNIC1", "NHI_ETHNIC2", "NHI_ETHNIC3"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "REPORTDATE", "InputFormat", "dd/MM/yyyy HH:mm");
opts = setvaropts(opts, "EARLIESTDATE", "InputFormat", "dd/MM/yyyy HH:mm");
opts = setvaropts(opts, "ONSETDT", "InputFormat", "dd/MM/yyyy HH:mm");
opts = setvaropts(opts, "MODIFIEDDATETIME", "InputFormat", "dd/MM/yyyy HH:mm");
opts = setvaropts(opts, "LABCONFDATE", "InputFormat", "dd/MM/yyyy HH:mm");
opts = setvaropts(opts, "ISOLATIONFROMDATE", "InputFormat", "dd/MM/yyyy HH:mm");

% Import the data
covidallcasesnhcc20220213 = readtable(filename, opts);

end