function [] = writeOmiSummary(scenarioname, scenarios, scen_letters)

nscenarios = size(scenarios, 2);

% Summary matrix initialissation
[date0, VE, scenario] = deal(strings(nscenarios, 1));
[infections, reinfections, cases, hosp, peakBeds, deaths, ...
    maxPrev10, maxAvgCases7, PCdate, PBdate, ...
    infLow, infHigh, casesLow, casesHigh, hospLow, hospHigh, pBedsLow, pBedsHigh, deathsLow, deathsHigh] = deal(zeros(nscenarios, 1));
summary = table(scenario, VE, date0, infections, reinfections, ...
    cases, hosp, peakBeds, deaths, maxPrev10, maxAvgCases7, PCdate, PBdate, ...
    infLow, infHigh, casesLow, casesHigh, hospLow, hospHigh, pBedsLow, pBedsHigh, deathsLow, deathsHigh);

for jj = 1:nscenarios
    
%     scenario_letter = char(ceil(jj/length(changeTRto)) + 64);
    scenario_letter = char(jj + 64);
    scenario_letter = scen_letters(jj);
    
    immLevel = ["original", "low", "high", "vlow", "vvlow"];
    TRscenario = ["low", "med", "high", "high", "high", "high"];
    
    iTRscenario = scenarios(1, jj);
    idate0 = scenarios(2, jj);
    
    [dailyinfTS, dailycasesTS, dailyhospTS, cdeathsTS, hospbedsTS] = ...
        readOmiTimeseries(scenarioname, scenario_letter, TRscenario(iTRscenario), 1);
    
    filename_dailyreinf = append('timeseries/', scenarioname, '/scenario', scenario_letter, '_reinfTS_', TRscenario(iTRscenario), 'Trans.csv');
    dailyreinfTS = csvread(filename_dailyreinf);
    
    [~, pcmaxdate] = max(median(dailycasesTS, 1));
    [~, pbmaxdate] = max(median(hospbedsTS, 1));
    
    
    %     t1 = 14;
    %     t2 = 28;
    %     [pf, ~] = polyfit(t1:t2, log(mean(dailyinfTS(:, t1:t2), 1)), 1);
    %     dt = log(2) / pf(1);
    summary(jj, :) = {scenario_letter, ...
        immLevel(scenarios(3, jj)), datestr(idate0, "ddmmm"),...
        round(median(sum(dailyinfTS, 2))), ...
        round(sum(dailyreinfTS, 'all')), ...
        round(median(sum(dailycasesTS, 2))), ...
        round(median(sum(dailyhospTS, 2))), ...
        round(median(max(hospbedsTS, [], 2))), ...
        round(median(cdeathsTS(:, end))), ...
        round(median(max(movsum(dailyinfTS, [0, 9], 2), [], 2)) / 5112280, 2), ...
        round(median(max(movsum(dailycasesTS, [0, 6], 2)./7, [], 2))), ...
        pcmaxdate, pbmaxdate...
        round(prctile(sum(dailyinfTS, 2), 2.5)), ...
        round(prctile(sum(dailyinfTS, 2), 97.5)), ...
        round(prctile(sum(dailycasesTS, 2), 2.5)), ...
        round(prctile(sum(dailycasesTS, 2), 97.5)), ...
        round(prctile(sum(dailyhospTS, 2), 2.5)), ...
        round(prctile(sum(dailyhospTS, 2), 97.5)), ...
        round(prctile(max(hospbedsTS, [], 2), 2.5)), ...
        round(prctile(max(hospbedsTS, [], 2), 97.5)), ...
        round(prctile(cdeathsTS(:, end), 2.5)), ...
        round(prctile(cdeathsTS(:, end), 97.5))};
        writetable(summary, append("summaries/", scenarioname, "_summary_", datestr(now,'yyyymmdd'), ".csv"))
end

end